version: "3.9"
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: characterCreator
    ports:
    - "5432:5432"
    volumes:
    - db:/var/lib/postgresql/data

  adminer:
    image: adminer:4
    restart: always
    ports:
    - "8090:8080"

volumes:
  db: