spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/characterCreator
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true